package ai.houyi.zhuque.dao;

import ai.houyi.zhuque.dao.model.AdGroup;
import ai.houyi.zhuque.dao.model.AdGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdGroupMapper {
    long countByExample(AdGroupExample example);

    int deleteByExample(AdGroupExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(AdGroup record);

    int insertSelective(AdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AdGroup selectOneByExample(AdGroupExample example);

    List<AdGroup> selectByExample(AdGroupExample example);

    AdGroup selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") AdGroup record, @Param("example") AdGroupExample example);

    int updateByExample(@Param("record") AdGroup record, @Param("example") AdGroupExample example);

    int updateByPrimaryKeySelective(AdGroup record);

    int updateByPrimaryKey(AdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AdGroup> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AdGroup> list, @Param("selective") AdGroup.Column ... selective);
}