package ai.houyi.zhuque.dao;

import ai.houyi.zhuque.dao.model.AdvertiserBill;
import ai.houyi.zhuque.dao.model.AdvertiserBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdvertiserBillMapper {
    long countByExample(AdvertiserBillExample example);

    int deleteByExample(AdvertiserBillExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(AdvertiserBill record);

    int insertSelective(AdvertiserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AdvertiserBill selectOneByExample(AdvertiserBillExample example);

    List<AdvertiserBill> selectByExample(AdvertiserBillExample example);

    AdvertiserBill selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") AdvertiserBill record, @Param("example") AdvertiserBillExample example);

    int updateByExample(@Param("record") AdvertiserBill record, @Param("example") AdvertiserBillExample example);

    int updateByPrimaryKeySelective(AdvertiserBill record);

    int updateByPrimaryKey(AdvertiserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AdvertiserBill> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AdvertiserBill> list, @Param("selective") AdvertiserBill.Column ... selective);
}