package ai.houyi.zhuque.dao;

import ai.houyi.zhuque.dao.model.AdvertiserQualification;
import ai.houyi.zhuque.dao.model.AdvertiserQualificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdvertiserQualificationMapper {
    long countByExample(AdvertiserQualificationExample example);

    int deleteByExample(AdvertiserQualificationExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(AdvertiserQualification record);

    int insertSelective(AdvertiserQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_qualification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AdvertiserQualification selectOneByExample(AdvertiserQualificationExample example);

    List<AdvertiserQualification> selectByExample(AdvertiserQualificationExample example);

    AdvertiserQualification selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") AdvertiserQualification record, @Param("example") AdvertiserQualificationExample example);

    int updateByExample(@Param("record") AdvertiserQualification record, @Param("example") AdvertiserQualificationExample example);

    int updateByPrimaryKeySelective(AdvertiserQualification record);

    int updateByPrimaryKey(AdvertiserQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_qualification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AdvertiserQualification> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertiser_qualification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AdvertiserQualification> list, @Param("selective") AdvertiserQualification.Column ... selective);
}