package ai.houyi.zhuque.dao;

import ai.houyi.zhuque.dao.model.AgentBill;
import ai.houyi.zhuque.dao.model.AgentBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentBillMapper {
    long countByExample(AgentBillExample example);

    int deleteByExample(AgentBillExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(AgentBill record);

    int insertSelective(AgentBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AgentBill selectOneByExample(AgentBillExample example);

    List<AgentBill> selectByExample(AgentBillExample example);

    AgentBill selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") AgentBill record, @Param("example") AgentBillExample example);

    int updateByExample(@Param("record") AgentBill record, @Param("example") AgentBillExample example);

    int updateByPrimaryKeySelective(AgentBill record);

    int updateByPrimaryKey(AgentBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AgentBill> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AgentBill> list, @Param("selective") AgentBill.Column ... selective);
}