package ai.houyi.zhuque.dao;

import ai.houyi.zhuque.dao.model.Campaign;
import ai.houyi.zhuque.dao.model.CampaignExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CampaignMapper {
    long countByExample(CampaignExample example);

    int deleteByExample(CampaignExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Campaign record);

    int insertSelective(Campaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Campaign selectOneByExample(CampaignExample example);

    List<Campaign> selectByExample(CampaignExample example);

    Campaign selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Campaign record, @Param("example") CampaignExample example);

    int updateByExample(@Param("record") Campaign record, @Param("example") CampaignExample example);

    int updateByPrimaryKeySelective(Campaign record);

    int updateByPrimaryKey(Campaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Campaign> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Campaign> list, @Param("selective") Campaign.Column ... selective);
}