package ai.houyi.zhuque.dao;

import ai.houyi.zhuque.dao.model.Creative;
import ai.houyi.zhuque.dao.model.CreativeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreativeMapper {
    long countByExample(CreativeExample example);

    int deleteByExample(CreativeExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Creative record);

    int insertSelective(Creative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creative
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Creative selectOneByExample(CreativeExample example);

    List<Creative> selectByExample(CreativeExample example);

    Creative selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Creative record, @Param("example") CreativeExample example);

    int updateByExample(@Param("record") Creative record, @Param("example") CreativeExample example);

    int updateByPrimaryKeySelective(Creative record);

    int updateByPrimaryKey(Creative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creative
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Creative> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creative
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Creative> list, @Param("selective") Creative.Column ... selective);
}