package ai.houyi.zhuque.dao;

import ai.houyi.zhuque.dao.model.Dsp;
import ai.houyi.zhuque.dao.model.DspExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DspMapper {
    long countByExample(DspExample example);

    int deleteByExample(DspExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Dsp record);

    int insertSelective(Dsp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Dsp selectOneByExample(DspExample example);

    List<Dsp> selectByExample(DspExample example);

    Dsp selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") Dsp record, @Param("example") DspExample example);

    int updateByExample(@Param("record") Dsp record, @Param("example") DspExample example);

    int updateByPrimaryKeySelective(Dsp record);

    int updateByPrimaryKey(Dsp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Dsp> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Dsp> list, @Param("selective") Dsp.Column ... selective);
}