package ai.houyi.zhuque.dao.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

public class Menu {
	private Integer id;

	private Integer pid;

	private String name;

	private String icon;

	private String url;

	private Date createTime;

	private Date updateTime;
	private List<Menu> children;

	public List<Menu> getChildren() {
		return children;
	}

	public void setChildren(List<Menu> children) {
		this.children = children;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table menu
	 *
	 * @mbg.generated
	 * @project https://github.com/itfsw/mybatis-generator-plugin
	 */
	public static Menu.Builder builder() {
		return new Menu.Builder();
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table menu
	 *
	 * @mbg.generated
	 * @project https://github.com/itfsw/mybatis-generator-plugin
	 */
	public static class Builder {
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private Menu obj;

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public Builder() {
			this.obj = new Menu();
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of
		 * the database column menu.id
		 *
		 * @param id the value for menu.id
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public Builder id(Integer id) {
			obj.setId(id);
			return this;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of
		 * the database column menu.pid
		 *
		 * @param pid the value for menu.pid
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public Builder pid(Integer pid) {
			obj.setPid(pid);
			return this;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of
		 * the database column menu.name
		 *
		 * @param name the value for menu.name
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public Builder name(String name) {
			obj.setName(name);
			return this;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of
		 * the database column menu.icon
		 *
		 * @param icon the value for menu.icon
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public Builder icon(String icon) {
			obj.setIcon(icon);
			return this;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of
		 * the database column menu.url
		 *
		 * @param url the value for menu.url
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public Builder url(String url) {
			obj.setUrl(url);
			return this;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of
		 * the database column menu.create_time
		 *
		 * @param createTime the value for menu.create_time
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public Builder createTime(Date createTime) {
			obj.setCreateTime(createTime);
			return this;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of
		 * the database column menu.update_time
		 *
		 * @param updateTime the value for menu.update_time
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public Builder updateTime(Date updateTime) {
			obj.setUpdateTime(updateTime);
			return this;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public Menu build() {
			return this.obj;
		}
	}

	/**
	 * This enum was generated by MyBatis Generator. This enum corresponds to the
	 * database table menu
	 *
	 * @mbg.generated
	 * @project https://github.com/itfsw/mybatis-generator-plugin
	 */
	public enum Column {
		id("id", "id", "INTEGER", false), pid("pid", "pid", "INTEGER", false), name("name", "name", "VARCHAR", false),
		icon("icon", "icon", "VARCHAR", false), url("url", "url", "VARCHAR", false),
		createTime("create_time", "createTime", "TIMESTAMP", false),
		updateTime("update_time", "updateTime", "TIMESTAMP", false);

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private static final String BEGINNING_DELIMITER = "\"";

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private static final String ENDING_DELIMITER = "\"";

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private final String column;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private final boolean isColumnNameDelimited;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private final String javaProperty;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private final String jdbcType;

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String value() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String getValue() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String getJavaProperty() {
			return this.javaProperty;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String getJdbcType() {
			return this.jdbcType;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
			this.column = column;
			this.javaProperty = javaProperty;
			this.jdbcType = jdbcType;
			this.isColumnNameDelimited = isColumnNameDelimited;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String desc() {
			return this.getEscapedColumnName() + " DESC";
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String asc() {
			return this.getEscapedColumnName() + " ASC";
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public static Column[] excludes(Column... excludes) {
			ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
			if (excludes != null && excludes.length > 0) {
				columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
			}
			return columns.toArray(new Column[] {});
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to
		 * the database table menu
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String getEscapedColumnName() {
			if (this.isColumnNameDelimited) {
				return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER)
						.toString();
			} else {
				return this.column;
			}
		}
	}
}